app/models.py
from app import db
from enum import Enum
from datetime import date


# grad odakle krecemo
# adresa di se goste kupi (google api ogranicava grad)
# grad dokle idemo
# adresa di se goste vodi (google api ogranicava grad)
# sredstvo
# cijena(eur)
# dvosmjerno - boolean
# kolicina osoba
# datum

class Vehicles(Enum):
    Limo = 1
    Minivan = 2
    Minibus = 3


class Transfer(db.Model):
    id = db.Column(db.Integer, primary_key=True)
    dptr = db.Column(db.String(255), nullable=False)
    dptr_addr = db.Column(db.String(255), nullable=False)
    dptr_date = db.Column(db.Date, nullable=False)
    dest = db.Column(db.String(255), nullable=False)
    dest_addr = db.Column(db.String(255), nullable=False)
    vehicle = db.Column(db.Enum(Vehicles), nullable=False)  # TODO: vidi kako ovo sranje radi
    price = db.Column(db.Float(precision=2), nullable=False)  # EURO
    is_twoway = db.Column(db.Boolean, default=False)
    num_of_pass = db.Column(db.Integer, nullable=False)
    contact_email = db.Column(db.String(255), nullable=False)

app/__init__.py
import os
import googlemaps
from flask import Flask
from flask_mail import Mail
from flask_sqlalchemy import SQLAlchemy
from app.config import TestingConfig, DevelopmentConfig, ProductionConfig


app = Flask(__name__)
app.config.from_object(DevelopmentConfig)

db = SQLAlchemy()

gmaps = googlemaps.Client(key=os.environ.get("GOOGLE_API_KEY"))

mail = Mail()

from app.errors.handlers import errors
from app.home.routes import home

app.register_blueprint(errors)
app.register_blueprint(home)


def create_app():
    app = Flask(__name__)
    app.config.from_object(ProductionConfig if os.environ.get(
        "PRODUCTION", "false").lower() == 'true' else DevelopmentConfig)

    db.init_app(app)
    mail.init_app(app)

    from app.errors.handlers import errors
    from app.home.routes import home

    app.register_blueprint(errors)
    app.register_blueprint(home)

    return app

app/home/routes.py
from app import db
from datetime import date
from app.models import Vehicles, Transfer
from flask import Blueprint, render_template, request, redirect, url_for, abort
from app.home.utils import get_available_vehicles, calculate_distance, get_offers, send_transfer_data_mail, calculate_price_final


home = Blueprint('home', __name__)


@home.route('/', methods=['GET', 'POST'])
def homepage():

    today = date.today()

    if request.method == "POST":
        departure = request.form.get("departure")
        destination = request.form.get("destination")
        num_of_pass = request.form.get("number_of_passengers")
        departure_date = request.form.get("departure_date")

        return redirect(url_for("home.vehicles",
                        departure=departure,
                        destination=destination,
                        num_of_pass=num_of_pass,
                        departure_date=departure_date))

    return render_template('home.html', title='Home', today=today)


@home.route('/transfer/<string:departure>/<string:destination>/<int:num_of_pass>/<string:departure_date>')
def vehicles(departure, destination, num_of_pass, departure_date):

    available_vehicles = get_available_vehicles(num_of_pass)
    distance = calculate_distance(departure, destination)

    offers = get_offers(available_vehicles, distance)

    return render_template("vehicles.html",
                           title="Vehicles",
                           offers=offers,
                           departure=departure,
                           destination=destination,
                           num_of_pass=num_of_pass,
                           departure_date=departure_date
                           )


@home.route('/transfer/<string:departure>/<string:destination>/<int:num_of_pass>/<string:departure_date>/<string:vehicle>', methods=['GET', 'POST'])
def transfer_data(departure, destination, num_of_pass, departure_date, vehicle):

    today = date.today()

    if vehicle not in [v.name for v in Vehicles]:
        abort(404)

    if request.method == "POST":
        dptr = request.form.get("departure")
        dptr_addr = request.form.get("dropoff-address")
        dptr_date = request.form.get("departure_date")
        dest = request.form.get("destination")
        dest_addr = request.form.get("pickup-address")
        vehicle_enum = Vehicles.__dict__.get(vehicle)
        is_twoway = True if request.form.get("is_twoway") == "Yes" else False
        price = calculate_price_final(vehicle, dptr, dest, is_twoway)
        num_of_pass = request.form.get("number_of_passengers")
        contact_email = request.form.get("email")

        transfer = Transfer(
            dptr=dptr,
            dptr_addr=dptr_addr,
            dptr_date=dptr_date,
            dest=dest,
            dest_addr=dest_addr,
            vehicle=vehicle_enum,
            price=price,
            is_twoway=is_twoway,
            num_of_pass=num_of_pass,
            contact_email=contact_email
        )
        db.session.add(transfer)
        db.session.commit()

        send_transfer_data_mail(transfer)

        return render_template("thank_you.html")
    else:
        return render_template("transfer_details.html",
                               title="Transfer Details",
                               today=today,
                               departure=departure,
                               destination=destination,
                               num_of_pass=num_of_pass,
                               )


# @home.route("/thankyou")
# def thankyou():
#     return render_template("thank_you.html")

app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">

    {% if title %}
    <title>Transferio - {{ title }}</title>
    {% else %}
    <title>Transferio</title>
    {% endif %}

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous"> -->
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='css/main.css') }}">
    <link href='https://fonts.googleapis.com/css?family=Poppins:300,400,500,600,700,800,900&subset=latin-ext' rel='stylesheet' type='text/css'>


<body>

    <nav>
        <div class="container">
            <div class="nav">
                <a href="/" class="logo">
                    transfer.io
                </a>
            </div>
        </div>
    </nav>

    {% block content %}
    {% endblock %}

</body>

</html>

app/templates/error.html
{% extends "base.html" %}
{% block content %}

<header class="container header header-booking">
    <div class="container"><div class="header-row">
            <a class="button white header-selection">{{ err_msg }}</a>
        </div>
    </div>
</header>

{% endblock content %}

app/templates/home.html
{% extends "base.html" %}
{% block content %}

    <header class="container header header--form back header--index">
        <div class="container">
            
            <h1 class="header-title">transfer.io - Croatian Transfer Service</h1>
            <form action="" method="post" class="header-form">
                        <div>
                    <label>Where from?</label>
                    <input type="text" placeholder="Enter your destination" id="departure" name="departure" required>
                </div>
                <div>
                    <label>Where to?</label>
                    <input type="text" placeholder="Enter your destination" id="destination" name="destination" required>
                </div>
                <div>
                    <label>When?</label>
                    <input type="date" id="departure_date" name="departure_date" min="{{ today.strftime('%Y-%m-%d') }}" value="{{ today.strftime('%Y-%m-%d') }}">
                </div>
                <div>
                    <label>Number of Passengers</label>
                    <input type="number" id="number_of_passengers" name="number_of_passengers" min="1" max="28" value="1" onkeydown="return false" required>
                </div>
                
                <button class="button" type="submit">Search transfer</button>
            </form>
            
        </div>
    </header>

    <script src="{{ url_for('static', filename="js/homeAutocomplete.js") }}"></script>
    <script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARqMbM-cAL_nF77CXZZK07BWzDxlYFgIk&libraries=places&callback=initAutocomplete" defer> </script>


{% endblock content %}

app/templates/thank_you.html
{% extends "base.html" %}
{% block content %}


<header class="container header header-booking">
    <div class="container">
        <div class="header-row">
        </div>
    </div>
</header>

<main class="container main">
    <ul class="container main-nav">
        <li class="fourth visible active">
            <a id="thankyou">
                THANK YOU!<br>
                YOU WILL RECIEVE AN EMAIL REGARDING YOUR RESERVATION SHORTLY.
            </a>
        </li>
    </ul>
</main>
{% endblock content %}

app/templates/transfer_details.html
{% extends "base.html" %}
{% block content %}


<header class="container header header-booking">
    <div class="container"><div class="header-row">
            <a class="button white header-selection">Transfer Details</a>
        </div>
    </div>
</header>

<section class="container main-form new-form clearfix">
    <div class="paths visible-path">
        <form action="" method="post" class="clearfix form form-travel active visible">
            <div class="row">
                <div class="col-md-4">
                    <label>Pick up location</label>
                    <span class="custom-combobox">
                        <input id="departure" name="departure" class="custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left ui-autocomplete-input" placeholder="Enter your starting point" value="{{ departure }}" required>
                    </span>
                </div>
                <div class="col-md-4">
                    <label>Drop off location</label>
                    <span class="custom-combobox">
                        <input id="destination" name="destination" class="custom-combobox-input ui-widget ui-widget-content ui-state-default ui-corner-left ui-autocomplete-input" placeholder="Enter your destination" value="{{ destination }}" required>
                    </span>
                </div>
                <div class="col-md-4">
                    <div class="col-xs-12 col-sm-6 right-radius-none">
                        <label>Pickup date</label>
                    <input type="date" id="departure_date" name="departure_date" min="{{ today.strftime('%Y-%m-%d') }}" value="{{ today.strftime('%Y-%m-%d') }}" required>
                    </div>
                    <div class="col-xs-12 col-sm-6 left-radius-none">
                        <label>Two way travel</label>
                        <select required id="is_twoway" name="is_twoway">
                            <option value="No" selected>No</option>
                            <option value="Yes">Yes</option>
                        </select>
                    </div>
            </div>
            <div class="row">
                <div class="col-md-3">
                    <label>Pick up address</label>
                    <input required type="text" name="pickup-address" placeholder="Fill in your address">
                </div>
                <div class="col-md-3">
                    <label>Drop off address</label>
                    <input required type="text" name="dropoff-address" placeholder="Fill in your address">
                </div>
                <div class="col-md-3">
                    <label>Ammount of Passengers</label>
                    <input type="number" id="number_of_passengers" name="number_of_passengers" min="1" max="28" value="{{ num_of_pass }}" onkeydown="return false" required>
                    </div>
                    <div class="col-md-3">
                        <label>Email</label>
                        <input type="email" name="email" placeholder="Your email" required>
                    </div>
            </div>
            <div class="row display-return">
                <div class="col-md-8 add-return-fields">
                </div>
                <div class="col-md-4">
                </div>
            </div>
            <div class="row m-top-48">
                <div class="col-md-4">
                </div>
                <div class="col-md-4">
                </div>
                <div class="col-md-4 back-next">
                    <button class="col-md-12 button blue next" type="submit" id="next-1">Next</button>
                </div>
            </div>
        </form>
    </div>
</section>
<script src="{{ url_for('static', filename="js/homeAutocomplete.js") }}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyARqMbM-cAL_nF77CXZZK07BWzDxlYFgIk&libraries=places&callback=initAutocomplete" defer> </script>

{% endblock content %}

app/templates/vehicles.html
{% extends "base.html" %}
{% block content %}


<header class="container header header-booking">
    <div class="container"><div class="header-row">
            <a class="button white header-selection">Available Vehicles</a>
        </div>
    </div>
</header>

<section class="container main-form new-form clearfix">

    {% for offer in offers %}

        <div class="pickup-vehicle" >
            <div class="col-wrapper">
                <div class="col-md-4">
                    {%  if "Limo" == offer["vehicle_type"] %}
                    <img src="{{ url_for('static', filename='img/limo.png') }}" class="lazyloaded" data-ll-status="loaded">
                    {%  elif "Minivan" == offer["vehicle_type"] %}
                    <img src="{{ url_for('static', filename='img/minivan.png') }}" class="lazyloaded" data-ll-status="loaded">
                    {%  elif "Minibus" == offer["vehicle_type"] %}
                    <img src="{{ url_for('static', filename='img/minibus.png') }}" class="lazyloaded" data-ll-status="loaded">
                    {% endif %}
                </div>
                <div class="col-md-3">
                    <h3>{{ offer["vehicle_type"] }}</h3>
                    <p>Vehicle type</p>
                </div>
                <div class="col-md-2">
                    <h3>{{ offer["max_num_of_pass"] }}</h3>
                    <p>Max. Passengers</p>
                </div>
                <div class="col-md-3">
                    <span id="vanLuxVClassPriceEur">{{ offer["price"] }} €</span>
                    </h3>
                    <p>Price</p>
                </div>
            </div>
            <div class="right-section">
                <div class="dot-border">
                    <div class="circle-top">
                    </div><div class="bord">
                    </div><div class="circle-bot">
                    </div>
                </div>
                <div class="button-wrapper">
                    <a href="{{ url_for('home.transfer_data', departure=departure, destination=destination, num_of_pass=num_of_pass, departure_date=departure_date, vehicle=offer['vehicle_type']) }}">
                        <button class="select-car">select</button>
                    </a>
                </div>
            </div>
        </div>

    {% endfor %}

</section>

{% endblock content %}